### ISSUE TITLE
Trouble with drop items

### ISSUE THREAD

**Issue by Ollie31212** [GuilleX7/ExplodeAny#21]
Hi, once my blocks have exploded they dont drop. Ive tried editting the config ie: PackDroppedItems: true DropChance: 100.0 but im still unable to get blocks to drop

**Comment by GuilleX7** [comment]
Hi @Ollie31212 ! Could you please tell more info about your environment?

- Version of Eany you're using
- Server software (Spigot-based or Folia-based)

Blocks should drop whenever a given material's DropChance is set to 100.0, as you said. PackDroppedItems does not need to be enabled for it (actually, having it set to false will result in more "realistic" drops).

Feel free to reach out to my Discord if you need to further describe your case, I'll summarize it here.

**Comment by GuilleX7** [comment]
Closed due to stagnation. The described behaviour could not be reproduced.
