### ISSUE TITLE
1.21 Support

### ISSUE THREAD

**Issue by Daniel0scur0** [GuilleX7/ExplodeAny#25]
the plugin doesn't work on 1.21
Tested on Minecraft Version 1.21 | Plugin Version 1.9.0 and 1.10.0 | Software Paper
![2024-08-01_01 43 14](https://github.com/user-attachments/assets/2fc8315f-5f00-41cb-868a-6125b5d19b3b)
![2024-08-01_01 43 01](https://github.com/user-attachments/assets/59adc6cb-a265-4719-aba3-8a7f70a753cf)
![2024-08-01_01 43 08](https://github.com/user-attachments/assets/72b3b793-e352-44fa-a845-42dc3997ca5d)
![2024-08-01_01 43 13](https://github.com/user-attachments/assets/88bda10d-1ed4-4d93-bb38-746e52224fc0)

**Comment by GuilleX7** [comment]
It seems 1.21 brings some breaking changes regarding entity names. TNT (PRIMED_TNT), TNT minecarts (MINECART_TNT) and ender crystals (ENDER_CRYSTALS) don't work properly.
